# Generated by Django 2.0 on 2017-12-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='units',
            field=models.IntegerField(choices=[(0, 'Gram'), (1, 'Pieces')], default=0, null=True),
        ),
    ]
