# Generated by Django 2.0 on 2017-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_provide_basic_db_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='units',
            field=models.IntegerField(choices=[(0, 'Gram'), (1, 'Pieces'), (2, 'Tea spoon'), (3, 'Table spoon'), (4, 'Glass'), (5, 'Pinch')], default=0, null=True),
        ),
    ]
