# Generated by Django 2.0 on 2017-12-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171206_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Amount'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
